repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.263"
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format